### ISSUE TITLE
Puppet 5

### ISSUE THREAD

**Issue by yachub** [genebean/packer-templates#2]
@genebean, With the release of Puppet 5 I'm eager to start testing various modules with the new agent. Are you planning to either update or build new Vagrant boxes and Docker containers? I frequently use the Vagrant box [genebean/centos-7-puppet-agent](https://app.vagrantup.com/genebean/boxes/centos-7-puppet-agent/versions/1.3.1) for example.

Thanks!

**Comment by genebean** [comment]
I'm actually planning on pushing new boxes this weekend after some testing. :-)

**Comment by genebean** [comment]
`genebean/centos-7-puppet5` has been uploaded to https://app.vagrantup.com/genebean/boxes/centos-7-puppet5. New versions of all other boxes are being built right now.
